### ISSUE TITLE
Enhancement for plain text and html templates

### ISSUE THREAD

**Issue by jBOKA** [acelaya/ZF-AcMailer#210] opened 2018-09-18 10:32 UTC
NOT AN ISSUE

Hi Alejandro,

do you think it would make sense to add templating for plain text and html mails at the same time?

I found an issue about using a `Zend\Mime'Message` in the `setBody()` method of the `MailService`, which apparently does not exist anymore in the current version. It looks like the `MailService` API would force the user to create the whole `Mail` class from scratch.

Since the Mail would have to have a "multipart/alternate" between plaintext and html and an additional "multipart/mixed" if attachments are needed, this could be handled by your module with a few more lines of code. Templating would then just require one more config `template_plaintext` to provide this functionality and a little adjustment in the `EmailBuilder` I guess.

What do you think?

Best regards
Jakob

btw: Best module regarding ease of use, besides the plaintext/html issue this is the most convenient way of composing mails in Zend. Thanks for that!

**Comment by acelaya** [comment] 2018-09-18 18:09
I suppose it could make sense.

Would you be willing to contribute this improvement? Or at least some tests reproducing the issue.

**Comment by jBOKA** [comment] 2018-09-24 15:35
I'm using the module just now, if I can spare out the time, I'll try to create a PR soon. Otherwise I'll let you know, so you can close the issue.

**Comment by acelaya** [comment] 2018-09-24 15:56
Oh, don't worry. If you can do it, that's great, but if not, I'll definitely try to investigate the issue myself. I don't mean to just close it :)

I asked you to do it because I'm currently focused in other things and it will probably take me a few weeks at least to have the time to approach this.

**Comment by jBOKA** [comment] 2018-09-26 14:39
I see. I'll stay in touch. Thanks

**Closed** 2019-10-06 11:24 UTC
