### ISSUE TITLE
Pass params to layout

### ISSUE THREAD

**Issue by cbichis** [acelaya/ZF-AcMailer#214] opened 2018-11-09 16:29 UTC
Hi,

As far as I searched there is no way to pass variables/params to layout.

By example the Email title should be included into layout. For this we need a way to pass it to layout.

**Comment by acelaya** [comment] 2018-11-09 16:30
All params passed to the template are passed to the layout as well. Just use those which apply on every place.

**Comment by cbichis** [comment] 2018-11-09 16:44
It doesnt seems to be the case.

`		$result = $this->mailService->send('email/delivery/leave', [
			'to' => ['email@gmail.com'],
			'template_params' => [
				'user' => 7890,
				'title' => 'Comanda ta a plecat deja spre tine!'
			]
		]);`

However, I am getting:

PHP Notice:  Undefined variable: title in /home/cristi/www/project/module/Frontend/view/layout/email.phtml on line 23

at that line is this:

`<h1><?php echo $title; ?></h1>`

**Comment by acelaya** [comment] 2018-11-09 16:54
Then it could be a bug. I'll need to check it

**Comment by cbichis** [comment] 2018-11-09 16:59
Overall a layout_params may be more appropriate, but your component is great enough that these are just very small improvements.

**Comment by acelaya** [comment] 2018-11-09 17:50
I'm affraid it cannot be implemented that way, because that would only make sense when using zend-view because of how it is implemented. If you are using any other renderer, that makes no sense.

I remember implementing the behavior which made params to be injected both in the layout and the template, but maybe there has been a regression.

**Comment by acelaya** [comment] 2018-11-09 17:58
Yep, it should be working.

Source: https://github.com/acelaya/ZF-AcMailer/blob/v7.3.1/src/View/MvcMailViewRenderer.php#L30
Test: https://github.com/acelaya/ZF-AcMailer/blob/v7.3.1/test/View/MvcMailViewRendererTest.php#L58

I'm going to do some manual testing and see what's going on.

**Comment by acelaya** [comment] 2018-11-09 18:34
I'm not sure what's going on, but it is working for me :thinking:

This is my layout (in `application/mail/layout.phtml`):

```php
<h1><?php echo $title ?></h1>
<div><?php echo $content ?></div>
```

This is my template (in `application/mail/template.phtml`):

```php
This is the content with user <b><?php echo $this->user ?></b>
```

This is my config:

```php
return [
    'acmailer_options' => [

        /*
         * This is where you configure all the emails that can be sent by the application.
         * You can create new ones at runtime, but this eases predefining emails that do not need to change
         */
        'emails' => [
            'email/delivery/leave' => [
                'from' => '...',
                'encoding' => 'utf-8',
                'subject' => 'Testing layout params',
                'template' => 'application/mail/template',
                'template_params' => [
                    'layout' => 'application/mail/layout',
                ],
            ],
        ],

        'mail_services' => [
            'default' => [
               // ...
            ],
        ],
    ],
];
```

And this is how I send the email:

```php
$result = $this->mailService->send('email/delivery/leave', [
    'to' => ['...'],
    'template_params' => [
        'user' => 7890,
        'title' => 'Comanda ta a plecat deja spre tine!'
    ]
]);
```

The resulting email contains the title inside the `h1` tag.

Could you share your config with me? (without credentials). Just to make sure everything is in place and try to make a real test as similar as possible.

**Comment by cbichis** [comment] 2018-11-09 19:06
`<?php

return [
    'acmailer_options' => [

        /*
         * This is where you configure all the emails that can be sent by the application.
         * You can create new ones at runtime, but this eases predefining emails that do not need to change
         */
        'emails' => [
			'base' => [
				'from' => 'notificari@fsdefsdfsdfds.ro',
				'from_name' => 'fsdfsdf',
				'bcc' => ['cristi@fsdfsdfsdfsd.ro'],
			],

			'email/delivery/leave' => [
				'extends' => 'base',
				'subject' => 'Comanda ta a plecat deja spre tine!',
				//'template' => 'email/delivery/leave',
				'template' => 'email/delivery/leave',
				'template_params' => [
					'layout' => 'layout/frontend/email',
				]
				//'template' => 'email/delivery-leave',
			],
        ],

        /*
         * This defines different services to send emails.
         * All of them will be capable of sending any of the previously configured emails.
         */
        'mail_services' => [
			'default' => [
				'transport' => 'smtp',
				'transport_options' => [
					'host' => 'mail.fdfdfsdsdsd.ro',
					'port' => 587,
					'connection_class' => 'login',
					'connection_config' => [
						'username' => 'mail-test@fsdfsdfsdfd.ro',
						'password' => 'dgfgdfsdsdfsdfdsfds',
						'ssl' => 'tls',
					],
				],
			],

            ],
        ],

    ],
];`

**Comment by acelaya** [comment] 2018-11-10 10:49
Working too...

The only thing that comes to my mind is that there's some external element modifying the params somehow.

Do you have any mail listener configured? Do you have any listener on the template renderer that could be interfering?

I would recommend you to do an isolated test just to make sure. I have been using a fresh skeleton application, where I have only installed this module. Then in the `IndexController` I have injected the mail service and sent the email just before returning the `ViewModel`.

```php
namespace Application\Controller;

use AcMailer\Service\MailServiceInterface;
use Zend\Mvc\Controller\AbstractActionController;
use Zend\View\Model\ViewModel;

class IndexController extends AbstractActionController
{
    /**
     * @var MailServiceInterface
     */
    private $mailService;

    public function __construct(MailServiceInterface $mailService)
    {
        $this->mailService = $mailService;
    }

    public function indexAction()
    {
        $result = $this->mailService->send('email/delivery/leave', [
            'to' => ['...'],
            'template_params' => [
                'user' => 7890,
                'title' => 'Comanda ta a plecat deja spre tine!'
            ]
        ]);
        var_dump($result->getEmail()->getTemplateParams());

        return new ViewModel();
    }
}
```

The call to `var_dump` should print all the params, including the title.

If it works for you there, then we can keep investigating which external element is breaking this.

**Comment by cbichis** [comment] 2018-11-10 10:50
Thanks, I'll check.

Thank you for your time!

**Comment by acelaya** [comment] 2018-11-10 10:51
By the way, just came to my mind, but this was something which used to be broken and it was fixed in [v7.2.1](https://github.com/acelaya/ZF-AcMailer/releases/tag/v7.2.1).

Make sure you have that version at least, because previous to that version, this didn't work.

**Comment by cbichis** [comment] 2018-11-10 10:56
Almost certainly this is/was the issue. I had 7.0 set on composer.json. Will confirm later today.

**Comment by acelaya** [comment] 2018-11-10 11:00
Ok, perfect. Let me know when you have checked.

Also, if you want to update, you should be good to do it to the latest stable version (I try to follow semver, so no BC breaks have been introduced). You can use the `^7.0` constraint in combination with the composer.lock file.

If you see that something does not work after the update, follow the [CHANGELOG](https://github.com/acelaya/ZF-AcMailer/blob/master/CHANGELOG.md) to see everything which has been changed.

And of course, if something does not work as expected, let me know.

**Comment by acelaya** [comment] 2018-11-14 17:09
Hey @cbichis, wad this finally the issue?

**Comment by cbichis** [comment] 2018-11-15 09:43
I can't actually confirm as the project is stuck on PHP 7.0 so I cant upgrade to version compatible with 7.1....

**Comment by acelaya** [comment] 2018-11-15 18:13
PHP 7.0 is getting out of support in a couple weeks. You should probably try to convince whoever can make the decision to update to PHP 7.2 ;-)

**Comment by acelaya** [comment] 2018-11-22 17:08
I'm closing this for now. If you get to update to PHP ^7.1 and still face this issue with a newer AcMailer version, just let me know.

**Closed by acelaya** 2018-11-22 17:08 UTC
Labels: question
